use std::collections::HashMap;

pub fn get_element_ui_documents() -> HashMap<String, String> {
    let url = "http://element.eleme.io";
    let mut m = HashMap::with_capacity(60);

    m.insert("el-row".into(), format!("[element：{url}/#/zh-CN/component/layout]({url}/#/zh-CN/component/layout) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| gutter | 栅格间隔 | number | — | 0 |\n| type | 布局模式 | string | — | — |\n| justify | flex水平排列 | string | start/end/center/space-around/space-between | start |\n| align | flex垂直排列 | string | top/middle/bottom | top |"));
    m.insert("el-col".into(), format!("[element：{url}/#/zh-CN/component/layout]({url}/#/zh-CN/component/layout) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| span | 栅格占据列数 | number | — | 24 |\n| offset | 栅格左侧间隔格数 | number | — | 0 |"));
    m.insert("el-container".into(), format!("[element：{url}/#/zh-CN/component/container]({url}/#/zh-CN/component/container) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| direction | 子元素的排列方向 | string | horizontal / vertical | — |"));
    m.insert("el-header".into(), format!("[element：{url}/#/zh-CN/component/container]({url}/#/zh-CN/component/container) \n\n| 参数 | 说明 | 类型 | 默认值 |\n| :--- | :--- | :--- | :--- |\n| height | 顶栏高度 | string | 60px |"));
    m.insert("el-aside".into(), format!("[element：{url}/#/zh-CN/component/container]({url}/#/zh-CN/component/container) \n\n| 参数 | 说明 | 类型 | 默认值 |\n| :--- | :--- | :--- | :--- |\n| width | 侧边栏宽度 | string | 300px |"));
    m.insert("el-footer".into(), format!("[element：{url}/#/zh-CN/component/layout]({url}/#/zh-CN/component/layout) \n\n| 参数 | 说明 | 类型 | 默认值 |\n| :--- | :--- | :--- | :--- |\n| height | 底栏高度 | string | 60px |"));
    m.insert("el-button".into(), format!("[element：{url}/#/zh-CN/component/button]({url}/#/zh-CN/component/button) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| size | 尺寸 | string | medium/small/mini | — |\n| type | 类型 | string | primary/success/warning/danger/info/text | — |\n| plain | 朴素按钮 | boolean | — | false |\n| round | 圆角按钮 | boolean | — | false |\n| loading | 加载中 | boolean | — | false |\n| disabled | 禁用 | boolean | — | false |"));
    m.insert("el-radio".into(), format!("[element：{url}/#/zh-CN/component/radio]({url}/#/zh-CN/component/radio) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| label | Radio的value | string/number/boolean | — | — |\n| disabled | 是否禁用 | boolean | — | false |\n| border | 显示边框 | boolean | — | false |\n| size | 尺寸 | string | medium/small/mini | — |"));
    m.insert("el-checkbox".into(), format!("[element：{url}/#/zh-CN/component/checkbox]({url}/#/zh-CN/component/checkbox) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| label | 选中状态的值 | string/number/boolean | — | — |\n| disabled | 是否禁用 | boolean | — | false |\n| checked | 当前是否勾选 | boolean | — | false |"));
    m.insert("el-input".into(), format!("[element：{url}/#/zh-CN/component/input]({url}/#/zh-CN/component/input) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| type | 类型 | string | text/textarea | text |\n| v-model | 绑定值 | string/number | — | — |\n| placeholder | 占位文本 | string | — | — |\n| clearable | 是否可清空 | boolean | — | false |\n| disabled | 禁用 | boolean | — | false |\n| size | 尺寸 | string | medium/small/mini | — |"));
    m.insert("el-select".into(), format!("[element：{url}/#/zh-CN/component/select]({url}/#/zh-CN/component/select) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| v-model | 绑定值 | — | — | — |\n| multiple | 是否多选 | boolean | — | false |\n| disabled | 是否禁用 | boolean | — | false |\n| clearable | 是否可清空 | boolean | — | false |\n| filterable | 是否可搜索 | boolean | — | false |\n| placeholder | 占位符 | string | — | 请选择 |"));
    m.insert("el-option".into(), format!("[element：{url}/#/zh-CN/component/select]({url}/#/zh-CN/component/select) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| value | 选项的值 | string/number/object | — | — |\n| label | 选项的标签 | string/number | — | — |\n| disabled | 是否禁用 | boolean | — | false |"));
    m.insert("el-form".into(), format!("[element：{url}/#/zh-CN/component/form]({url}/#/zh-CN/component/form) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| model | 表单数据对象 | object | — | — |\n| rules | 验证规则 | object | — | — |\n| inline | 行内模式 | boolean | — | false |\n| label-width | 标签宽度 | string | — | — |\n| size | 尺寸 | string | medium/small/mini | — |"));
    m.insert("el-form-item".into(), format!("[element：{url}/#/zh-CN/component/form]({url}/#/zh-CN/component/form) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| prop | 表单域model字段 | string | — | — |\n| label | 标签文本 | string | — | — |\n| label-width | 标签宽度 | string | — | — |\n| required | 是否必填 | boolean | — | false |"));
    m.insert("el-table".into(), format!("[element：{url}/#/zh-CN/component/table]({url}/#/zh-CN/component/table) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| data | 显示的数据 | array | — | — |\n| height | 高度 | string/number | — | — |\n| stripe | 斑马纹 | boolean | — | false |\n| border | 纵向边框 | boolean | — | false |\n| size | 尺寸 | string | medium/small/mini | — |"));
    m.insert("el-table-column".into(), format!("[element：{url}/#/zh-CN/component/table]({url}/#/zh-CN/component/table) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| type | 列类型 | string | selection/index/expand | — |\n| label | 标题 | string | — | — |\n| prop | 字段名 | string | — | — |\n| width | 宽度 | string | — | — |\n| sortable | 排序 | boolean/string | true/false/custom | false |"));
    m.insert("el-tag".into(), format!("[element：{url}/#/zh-CN/component/tag]({url}/#/zh-CN/component/tag) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| type | 主题 | string | success/info/warning/danger | — |\n| closable | 可关闭 | boolean | — | false |\n| size | 尺寸 | string | medium/small/mini | — |"));
    m.insert("el-dialog".into(), format!("[element：{url}/#/zh-CN/component/dialog]({url}/#/zh-CN/component/dialog) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| visible | 是否显示 | boolean | — | false |\n| title | 标题 | string | — | — |\n| width | 宽度 | string | — | 50% |\n| before-close | 关闭前的回调 | function(done) | — | — |"));
    m.insert("el-pagination".into(), format!("[element：{url}/#/zh-CN/component/pagination]({url}/#/zh-CN/component/pagination) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| page-size | 每页条数 | number | — | 10 |\n| total | 总条目数 | number | — | — |\n| current-page | 当前页数 | number | — | 1 |\n| layout | 组件布局 | string | — | prev,pager,next,jumper,total |"));
    m.insert("el-menu".into(), format!("[element：{url}/#/zh-CN/component/menu]({url}/#/zh-CN/component/menu) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| mode | 模式 | string | horizontal/vertical | vertical |\n| default-active | 当前激活菜单 | string | — | — |"));
    m.insert("el-tabs".into(), format!("[element：{url}/#/zh-CN/component/tabs]({url}/#/zh-CN/component/tabs) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| type | 风格类型 | string | card/border-card | — |\n| v-model | 绑定值 | string | — | — |"));
    m.insert("el-alert".into(), format!("[element：{url}/#/zh-CN/component/alert]({url}/#/zh-CN/component/alert) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| title | 标题 | string | — | — |\n| type | 主题 | string | success/warning/info/error | info |\n| closable | 可关闭 | boolean | — | true |"));
    m.insert("el-tree".into(), format!("[element：{url}/#/zh-CN/component/tree]({url}/#/zh-CN/component/tree) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| data | 展示数据 | array | — | — |\n| props | 配置选项 | object | — | — |\n| show-checkbox | 可被选择 | boolean | — | false |"));
    m.insert("el-upload".into(), format!("[element：{url}/#/zh-CN/component/upload]({url}/#/zh-CN/component/upload) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| action | 上传地址(必选) | string | — | — |\n| multiple | 多选文件 | boolean | — | — |\n| limit | 最大上传数 | number | — | — |"));
    m.insert("el-cascader".into(), format!("[element：{url}/#/zh-CN/component/cascader]({url}/#/zh-CN/component/cascader) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| options | 数据源 | array | — | — |\n| v-model | 选中值 | array | — | — |\n| placeholder | 占位文本 | string | — | 请选择 |"));
    m.insert("el-switch".into(), format!("[element：{url}/#/zh-CN/component/switch]({url}/#/zh-CN/component/switch) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| v-model | 绑定值 | boolean | — | — |\n| disabled | 禁用 | boolean | — | false |\n| active-color | 打开时的背景色 | string | — | #409EFF |"));
    m.insert("el-rate".into(), format!("[element：{url}/#/zh-CN/component/rate]({url}/#/zh-CN/component/rate) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| v-model | 绑定值 | number | — | 0 |\n| max | 最大分值 | number | — | 5 |\n| disabled | 只读 | boolean | — | false |"));
    m.insert("el-progress".into(), format!("[element：{url}/#/zh-CN/component/progress]({url}/#/zh-CN/component/progress) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| percentage | 百分比(必填) | number | 0-100 | 0 |\n| type | 类型 | string | line/circle | line |"));
    m.insert("el-badge".into(), format!("[element：{url}/#/zh-CN/component/badge]({url}/#/zh-CN/component/badge) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| value | 显示值 | string/number | — | — |\n| max | 最大值 | number | — | — |\n| is-dot | 小圆点 | boolean | — | false |"));
    m.insert("el-drawer".into(), format!("[element：{url}/#/zh-CN/component/drawer]({url}/#/zh-CN/component/drawer) \n\n| 参数 | 说明 | 类型 | 可选值 | 默认值 |\n| :--- | :--- | :--- | :--- | :--- |\n| visible | 是否显示 | boolean | — | false |\n| title | 标题 | string | — | — |\n| direction | 打开方向 | string | rtl/ltr/ttb/btt | rtl |"));

    m
}
