use std::collections::HashMap;

pub fn get_snippets(ts: &str) -> HashMap<String, String> {
    let mut m = HashMap::with_capacity(70);
    m.insert("vnew".into(), format!("new Vue({{\n{ts}$1\n}})"));
    m.insert("vgsilent".into(), "Vue.config.silent = ${1:true}".into());
    m.insert("vgeh".into(), format!("Vue.config.errorHandler = function (err, vm, info) {{\n{ts}${{1:// handle error}}\n}}"));
    m.insert("vgwh".into(), format!("Vue.config.warnHandler = function (msg, vm, trace) {{\n{ts}${{1:// handle warn}}\n}}"));
    m.insert("vgextend".into(), format!("Vue.extend({{\n{ts}template:${{1:template}}\n}})"));
    m.insert("vgnt".into(), format!("Vue.nextTick({{\n{ts}$1\n}})"));
    m.insert("vgset".into(), "Vue.set(${2:target}, ${3:key}, ${4:value})".into());
    m.insert("vgdelete".into(), "Vue.delete(${2:target}, ${3:key})".into());
    m.insert("vgdirective".into(), "Vue.directive(${2:id}${3:, [definition]})".into());
    m.insert("vgfilter".into(), "Vue.filter(${1:id}${2:, [definition]})".into());
    m.insert("vgcomponent".into(), "Vue.component(${1:id}${2:, [definition]})$0".into());
    m.insert("vguse".into(), "Vue.use(${1:plugin})$0".into());
    m.insert("vgmixin".into(), "Vue.mixin({${1:mixin}})".into());
    m.insert("vgcompile".into(), "Vue.compile(${1:template})".into());
    m.insert("vdata".into(), format!("data() {{\n{ts}return {{\n{ts}{ts}$1\n{ts}}}\n}},$0"));
    m.insert("vmounted".into(), format!("mounted () {{\n{ts}$1\n}}"));
    m.insert("vbm".into(), format!("beforeMount () {{\n{ts}$1\n}}"));
    m.insert("vcreated".into(), format!("created () {{\n{ts}$1\n}}"));
    m.insert("vbc".into(), format!("beforeCreate () {{\n{ts}$1\n}}"));
    m.insert("vupdated".into(), format!("updated () {{\n{ts}$1\n}}"));
    m.insert("vbu".into(), format!("beforeUpdate () {{\n{ts}$1\n}}"));
    m.insert("vactivated".into(), format!("activated () {{\n{ts}$1\n}}"));
    m.insert("vdeactivated".into(), format!("deactivated () {{\n{ts}$1\n}}"));
    m.insert("vbd".into(), format!("beforeDestroy () {{\n{ts}$1\n}}"));
    m.insert("vdestroyed".into(), format!("destroyed () {{\n{ts}$1\n}}"));
    m.insert("vprops".into(), format!("props: {{\n{ts}$1\n}}"));
    m.insert("vpd".into(), format!("propsData: {{\n{ts}$1\n}}"));
    m.insert("vcomputed".into(), format!("computed: {{\n{ts}$1\n}}"));
    m.insert("vmethods".into(), format!("methods: {{\n{ts}$1\n}}"));
    m.insert("vwatch".into(), format!("watch: {{\n{ts}$1\n}}"));
    m.insert("vwo".into(), format!("${{1:key}}: {{\n{ts}deep: ${{2:true}},\n{ts}immediate: ${{3:true}},\n{ts}handler: function (${{4:val}}, ${{5:oldVal}}) {{\n{ts}{ts}$6\n{ts}}}\n}},$0"));
    m.insert("vdirectives".into(), format!("directives: {{\n{ts}$1\n}}"));
    m.insert("vfilters".into(), format!("filters: {{\n{ts}$1\n}}"));
    m.insert("vcomponents".into(), format!("components: {{\n{ts}$1\n}}"));
    m.insert("vmixins".into(), "mixins:[$1],".into());
    m.insert("vprovide".into(), format!("provide: {{\n{ts}$1\n}}"));
    m.insert("vinject".into(), "inject: [$1],".into());
    m.insert("vmodel".into(), format!("model: {{\n{ts}prop: $1,\n{ts}event: $2\n}}"));
    m.insert("vrender".into(), format!("render(h) {{\n{ts}$1\n}},"));
    m.insert("vel".into(), "${1|this,vm|}.$el$2".into());
    m.insert("voptions".into(), "${1|this,vm|}.$options$2".into());
    m.insert("vparent".into(), "${1|this,vm|}.$parent$2".into());
    m.insert("vroot".into(), "${1|this,vm|}.$root$2".into());
    m.insert("vchildren".into(), "${1|this,vm|}.$children$2".into());
    m.insert("vslots".into(), "${1|this,vm|}.$slots$2".into());
    m.insert("vss".into(), format!("${{1|this,vm|}}.$scopedSlots.default({{\n{ts}$2\n}})"));
    m.insert("vrefs".into(), "${1|this,vm|}.$refs$2".into());
    m.insert("vis".into(), "${1|this,vm|}.$isServer$2".into());
    m.insert("vattrs".into(), "${1|this,vm|}.$attrs$2".into());
    m.insert("vlisteners".into(), "${1|this,vm|}.$listeners$2".into());
    m.insert("vset".into(), "${1|this,vm|}.$set(${2:target}, ${3:key}, ${4:value})".into());
    m.insert("vdelete".into(), "${1|this,vm|}.$delete(${2:target}, ${3:key})".into());
    m.insert("von".into(), "${1|this,vm|}.$on('${2:event}', ${3:callback})$4".into());
    m.insert("vonce".into(), "${1|this,vm|}.$once('${2:event}', ${3:callback})$4".into());
    m.insert("voff".into(), "${1|this,vm|}.$off('${2:event}', ${3:callback})$4".into());
    m.insert("vemit".into(), "${1|this,vm|}.$emit('${2:event}'${3:, args})$4".into());
    m.insert("vmount".into(), "${1|this,vm|}.$mount('$2')".into());
    m.insert("vfu".into(), "${1|this,vm|}.$forceUpdate()".into());
    m.insert("vdestroy".into(), "${1|this,vm|}.$destroy()$2".into());
    m.insert("vnt".into(), format!("${{1|this,vm|}}.$nextTick(() => {{\n{ts}$2\n}})"));
    m
}
