use std::collections::HashMap;

pub fn get_element_ui_tags(ts: &str) -> HashMap<String, String> {
    let mut m = HashMap::with_capacity(90);
    m.insert("el-col".into(), format!("<el-col :span=\"$1\">$2</el-col>"));
    m.insert("el-checkbox".into(), "<el-checkbox label=\"$1\">$2</el-checkbox>".into());
    m.insert("el-checkbox-group".into(), format!("<el-checkbox-group v-model=\"$1\">\n{ts}<el-checkbox label=\"$2\">$3</el-checkbox>\n</el-checkbox-group>"));
    m.insert("el-checkbox-button".into(), "<el-checkbox-button label=\"$1\">$2</el-checkbox-button>".into());
    m.insert("el-input".into(), "<el-input v-model=\"$1\" placeholder=\"$2\">$3</el-input>".into());
    m.insert("el-option".into(), "<el-option :label=\"$1\" :value=\"$2\">$3</el-option>".into());
    m.insert("el-option-group".into(), format!("<el-option-group v-for=\"$1\" :key=\"$2\">\n<el-option :label=\"$3\" :value=\"$4\"></el-option>$5\n</el-option-group>"));
    m.insert("el-cascader".into(), "<el-cascader :options=\"$1\" v-model=\"$2\">$3</el-cascader>".into());
    m.insert("el-color-picker".into(), "<el-color-picker v-model=\"$1\">$2</el-color-picker>".into());
    m.insert("el-form-item".into(), "<el-form-item label=\"$1\">$2</el-form-item>".into());
    m.insert("el-alert".into(), "<el-alert type=\"$1\" title=\"$2\">$3</el-alert>".into());
    m.insert("el-submenu".into(), format!("<el-submenu index=\"$1\">\n{ts}<el-menu-item index=\"$2\">$3</el-menu-item>$4\n</el-submenu>"));
    m.insert("el-menu-item-group".into(), format!("<el-menu-item-group>\n{ts}<el-menu-item index=\"$1\">$2</el-menu-item>$3\n</el-menu-item-group>"));
    m.insert("el-menu-item".into(), "<el-menu-item index=\"\"></el-menu-item>".into());
    m.insert("el-tab-pane".into(), "<el-tab-pane>$1</el-tab-pane>".into());
    m.insert("el-breadcrumb-item".into(), "<el-breadcrumb-item></el-breadcrumb-item>".into());
    m.insert("el-dropdown-menu".into(), "<el-dropdown-menu></el-dropdown-menu>".into());
    m.insert("el-step".into(), "<el-step title=\"$1\">$2</el-step>".into());
    m.insert("el-carousel".into(), format!("<el-carousel>\n{ts}<el-carousel-item>$1</el-carousel-item>\n</el-carousel>"));
    m.insert("el-carousel-item".into(), "<el-carousel-item>$1</el-carousel-item>".into());
    m.insert("el-collapse-item".into(), "<el-collapse-item name=\"$1\" title=\"$2\">$3</el-collapse-item>".into());
    m.insert("el-timeline-item".into(), "<el-timeline-item>$1</el-timeline-item>".into());
    m.insert("el-divider".into(), "<el-divider>$1</el-divider>".into());
    m.insert("el-alert:icon".into(), format!("<el-alert\n{ts}title=\"success\"\n{ts}type=\"success\"\n{ts}show-icon>\n</el-alert>"));
    m.insert("el-autocomplete".into(), "<el-autocomplete v-model=\"$1\" placeholder=\"\" :fetch-suggestions=\"fetchSuggestions\" @select=\"handleSelect\">\n</el-autocomplete>".into());
    m.insert("el-badge".into(), "<el-badge :value=\"$1\"/>".into());
    m.insert("el-badge:button".into(), format!("<el-badge :value=\"$1\">\n{ts}<el-button size=\"small\">$2</el-button>\n</el-badge>"));
    m.insert("el-badge:dot".into(), "<el-badge is-dot>$1</el-badge>".into());
    m.insert("el-breadcrumb".into(), format!("<el-breadcrumb separator=\"/\">\n{ts}<el-breadcrumb-item :to=\"{{ path: '/' }}\"></el-breadcrumb-item>\n{ts}<el-breadcrumb-item></el-breadcrumb-item>\n</el-breadcrumb>"));
    m.insert("el-button".into(), "<el-button type=\"primary\">$1</el-button>".into());
    m.insert("el-button-group".into(), format!("<el-button-group>\n{ts}<el-button type=\"primary\">$1</el-button>\n{ts}<el-button type=\"primary\">$2</el-button>\n</el-button-group>"));
    m.insert("el-card".into(), format!("<el-card>\n{ts}<div slot=\"header\">$1</div>\n{ts}<div></div>\n</el-card>"));
    m.insert("el-carousel:card".into(), format!("<el-carousel type=\"card\" height=\"150px\">\n{ts}<el-carousel-item>\n{ts}{ts}$1\n{ts}</el-carousel-item>\n</el-carousel>"));
    m.insert("el-collapse".into(), format!("<el-collapse v-model=\"${{1:activeName}}\" @change=\"${{2:collapseChange}}\">\n{ts}<el-collapse-item title=\"${{3:title}}\" name=\"${{4:name}}\">\n{ts}{ts}<div>$5</div>\n{ts}</el-collapse-item>\n</el-collapse>"));
    m.insert("el-date-picker".into(), "<el-date-picker v-model=\"$1\" type=\"date\" placeholder=\"${2:date}\"></el-date-picker>".into());
    m.insert("el-date-picker:datetime".into(), "<el-date-picker v-model=\"$1\" type=\"datetime\" placeholder=\"${2:datetime}\"></el-date-picker>".into());
    m.insert("el-dialog".into(), format!("<el-dialog\n{ts}title=\"\"\n{ts}:visible.sync=\"${{1:dialogVisible}}\"\n{ts}width=\"${{2:width}}\"\n{ts}:before-close=\"${{3:dialogBeforeClose}}\">\n{ts}<div>$4</div>\n{ts}<div slot=\"footer\">\n{ts}{ts}<el-button @click=\"dialogVisible = false\">取 消</el-button>\n{ts}{ts}<el-button type=\"primary\" @click=\"dialogVisible = false\">确 定</el-button>\n{ts}</div>\n</el-dialog>"));
    m.insert("el-dialog:form".into(), format!("<el-dialog\n{ts}title=\"\"\n{ts}:visible.sync=\"${{1:dialogVisible}}\"\n{ts}width=\"${{2:width}}\"\n{ts}:before-close=\"${{3:dialogBeforeClose}}\">\n{ts}<el-form :model=\"form\">\n{ts}{ts}<el-form-item label=\"\" :label-width=\"\">\n{ts}{ts}{ts}<el-input v-model=\"\"></el-input>\n{ts}{ts}</el-form-item>\n{ts}</el-form>\n{ts}<div slot=\"footer\">\n{ts}{ts}<el-button @click=\"dialogVisible = false\">取 消</el-button>\n{ts}{ts}<el-button type=\"primary\" @click=\"dialogVisible = false\">确 定</el-button>\n{ts}</div>\n</el-dialog>"));
    m.insert("el-dropdown".into(), format!("<el-dropdown>\n{ts}<el-button type=\"primary\">\n{ts}{ts}下拉菜单<i class=\"el-icon-arrow-down el-icon--right\"></i>\n{ts}</el-button>\n{ts}<el-dropdown-menu slot=\"dropdown\">\n{ts}{ts}<el-dropdown-item>黄金糕</el-dropdown-item>\n{ts}</el-dropdown-menu>\n</el-dropdown>"));
    m.insert("el-form".into(), format!("<el-form ref=\"${{1:form}}\" :model=\"${{2:form}}\" label-width=\"${{3:80px}}\">\n{ts}$4\n</el-form>"));
    m.insert("el-form:inline".into(), format!("<el-form :inline=\"true\" ref=\"${{1:form}}\" :model=\"${{2:form}}\" label-width=\"${{3:80px}}\">\n{ts}$4\n</el-form>"));
    m.insert("el-form-item:input".into(), format!("<el-form-item label=\"${{1:label}}\">\n{ts}<el-input v-model=\"${{2:model}}\"></el-input>\n</el-form-item>"));
    m.insert("el-form-item:checkbox".into(), format!("<el-form-item label=\"${{1:label}}\">\n{ts}<el-checkbox-group v-model=\"${{2:model}}\">\n{ts}{ts}<el-checkbox label=\"${{3:label}}\" name=\"${{4:name}}\"></el-checkbox>\n{ts}</el-checkbox-group>\n</el-form-item>"));
    m.insert("el-form-item:radio".into(), format!("<el-form-item label=\"${{1:label}}\">\n{ts}<el-radio-group v-model=\"${{2:model}}\">\n{ts}{ts}<el-radio label=\"${{3:label}}\"></el-radio>\n{ts}</el-radio-group>\n</el-form-item>"));
    m.insert("el-form-item:select".into(), format!("<el-form-item label=\"${{1:label}}\">\n{ts}<el-select v-model=\"${{2:model}}\" placeholder=\"${{3:placeholder}}\">\n{ts}{ts}<el-option label=\"${{4:label}}\" value=\"${{5:value}}\"></el-option>\n{ts}</el-select>\n</el-form-item>"));
    m.insert("el-form-item:switch".into(), format!("<el-form-item label=\"${{1:label}}\">\n<el-switch v-model=\"${{2:model}}\"></el-switch>\n</el-form-item>"));
    m.insert("el-form-item:textarea".into(), format!("<el-form-item label=\"${{1:label}}\">\n<el-input type=\"textarea\" v-model=\"${{2:model}}\"></el-input>\n</el-form-item>"));
    m.insert("el-input-number".into(), format!("<el-input-number v-model=\"$1\" @change=\"${{2:inputChange}}\" :min=\"${{3:1}}\" :max=\"${{4:10}}\" label=\"${{5:label}}\"></el-input-number>"));
    m.insert("el-input:textarea".into(), "<el-input type=\"textarea\" v-model=\"$1\" placeholder=\"$2\"></el-input>".into());
    m.insert("el-menu".into(), format!("<el-menu :default-active=\"${{1:activeIndex}}\" mode=\"horizontal\" @select=\"${{2:menuSelect}}\">\n{ts}<el-menu-item index=\"${{3:index}}\">$4</el-menu-item>\n</el-menu>"));
    m.insert("el-pagination".into(), format!("<el-pagination\n{ts}layout=\"prev, pager, next\"\n{ts}:total=\"50\">\n</el-pagination>"));
    m.insert("el-pagination:full".into(), format!("<el-pagination\n{ts}@size-change=\"handleSizeChange\"\n{ts}@current-change=\"handleCurrentChange\"\n{ts}:current-page=\"pageNum\"\n{ts}:page-sizes=\"[10, 20, 50]\"\n{ts}:page-size=\"pageSize\"\n{ts}layout=\"total, sizes, prev, pager, next, jumper\"\n{ts}:total=\"totalCount\">\n</el-pagination>"));
    m.insert("el-popover".into(), format!("<el-popover\n{ts}ref=\"popover1\"\n{ts}placement=\"top-start\"\n{ts}title=\"标题\"\n{ts}width=\"200\"\n{ts}trigger=\"hover\"\n{ts}content=\"这是一段内容\">\n</el-popover>"));
    m.insert("el-progress".into(), "<el-progress :percentage=\"${1:30}\"></el-progress>".into());
    m.insert("el-progress:circle".into(), "<el-progress type=\"circle\" :percentage=\"${1:30}\"></el-progress>".into());
    m.insert("el-progress:inside".into(), "<el-progress :text-inside=\"true\" :stroke-width=\"18\" :percentage=\"70\"></el-progress>".into());
    m.insert("el-radio".into(), "<el-radio v-model=\"radio\" label=\"${1:label}\">$2</el-radio>".into());
    m.insert("el-radio-button".into(), "<el-radio-button label=\"${1:label}\"></el-radio-button>".into());
    m.insert("el-radio-group".into(), format!("<el-radio-group v-model=\"${{1:model}}\">\n{ts}<el-radio :label=\"${{2:label}}\">$3</el-radio>\n</el-radio-group>"));
    m.insert("el-rate".into(), "<el-rate v-model=\"$1\"></el-rate>".into());
    m.insert("el-row".into(), format!("<el-row :gutter=\"${{1:10}}\">\n{ts}<el-col :span=\"${{2:6}}\">$3</el-col>\n</el-row>"));
    m.insert("el-select".into(), format!("<el-select v-model=\"model\" placeholder=\"\">\n{ts}<el-option\n{ts}{ts}v-for=\"item in options\"\n{ts}{ts}:key=\"item.value\"\n{ts}{ts}:label=\"item.label\"\n{ts}{ts}:value=\"item.value\">\n{ts}</el-option>\n</el-select>"));
    m.insert("el-slider".into(), "<el-slider v-model=\"${1:30}\"></el-slider>".into());
    m.insert("el-steps".into(), format!("<el-steps :active=\"active\" finish-status=\"success\">\n{ts}<el-step title=\"step1\"></el-step>\n</el-steps>"));
    m.insert("el-switch".into(), "<el-switch v-model=\"${1:model}\" active-color=\"${2:#13ce66}\" inactive-color=\"${3:#ff4949}\"></el-switch>".into());
    m.insert("el-tabs".into(), format!("<el-tabs v-model=\"${{1:activeName}}\" @tab-click=\"${{2:handleClick}}\">\n{ts}<el-tab-pane label=\"${{3:label}}\" name=\"${{4:name}}\">$5</el-tab-pane>\n</el-tabs>"));
    m.insert("el-tabs:card".into(), format!("<el-tabs type=\"card\" v-model=\"${{1:activeName}}\" @tab-click=\"${{2:handleClick}}\">\n{ts}<el-tab-pane label=\"${{3:label}}\" name=\"${{4:name}}\">$5</el-tab-pane>\n</el-tabs>"));
    m.insert("el-table".into(), format!("<el-table\n{ts}:data=\"${{1:data}}\"\n{ts}style=\"width: 100%\">\n{ts}<el-table-column\n{ts}{ts}prop=\"${{2:prop}}\"\n{ts}{ts}label=\"${{3:label}}\"\n{ts}{ts}width=\"${{4:width}}\">\n{ts}</el-table-column>\n</el-table>"));
    m.insert("el-table-column".into(), format!("<el-table-column\n{ts}header-align=\"center\"\n{ts}align=\"center\"\n{ts}prop=\"${{1:prop}}\"\n{ts}label=\"${{2:label}}\" >\n</el-table-column>"));
    m.insert("el-tag".into(), "<el-tag type=\"${1:success}\">$2</el-tag>".into());
    m.insert("el-tag:close".into(), "<el-tag closable type=\"${1:success}\">$2</el-tag>".into());
    m.insert("el-tooltip".into(), format!("<el-tooltip effect=\"dark\" content=\"$1\" placement=\"${{2:top}}\">\n{ts}<el-button>$3</el-button>\n</el-tooltip>"));
    m.insert("el-transfer".into(), format!("<el-transfer\n{ts}v-model=\"$1\"\n{ts}:data=\"$2\">\n</el-transfer>"));
    m.insert("el-tree".into(), format!("<el-tree\n{ts}:data=\"$1\"\n{ts}:props=\"$2\"\n{ts}@node-click=\"$3\">\n</el-tree>"));
    m.insert("el-tree:select".into(), format!("<el-tree\n{ts}show-checkbox\n{ts}:data=\"$1\"\n{ts}:props=\"$2\"\n{ts}@node-click=\"$3\">\n</el-tree>"));
    m.insert("el-upload".into(), format!("<el-upload\n{ts}action=\"\"\n{ts}:on-preview=\"\"\n{ts}:on-remove=\"\"\n{ts}:before-remove=\"\"\n{ts}multiple\n{ts}:limit=\"3\"\n{ts}:on-exceed=\"\"\n{ts}:file-list=\"[{{name: 'name', url: 'url'}}]\">\n{ts}<el-button size=\"small\" type=\"primary\">点击上传</el-button>\n{ts}<div slot=\"tip\" class=\"el-upload__tip\">只能上传jpg/png文件，且不超过500kb</div>\n</el-upload>"));
    m.insert("el-upload:avatar".into(), format!("<el-upload\n{ts}action=\"\"\n{ts}:show-file-list=\"false\"\n{ts}:on-success=\"\"\n{ts}:before-upload=\"\">\n{ts}<img v-if=\"imageUrl\" :src=\"imageUrl\">\n{ts}<i v-else class=\"el-icon-plus avatar-uploader-icon\"></i>\n</el-upload>"));
    m.insert("el-timeline".into(), format!("<el-timeline :reverse=\"reverse\">\n{ts}<el-timeline-item\n{ts}{ts}v-for=\"(activity, index) in activities\"\n{ts}{ts}:key=\"index\"\n{ts}{ts}:timestamp=\"activity.timestamp\">\n{ts}{ts}{{{{activity.content}}}}\n{ts}</el-timeline-item>\n</el-timeline>"));
    m.insert("el-calendar".into(), "<el-calendar v-model=\"${1:value}\"></el-calendar>".into());
    m.insert("el-image".into(), format!("<el-image\n{ts}style=\"${{1:width: 100px; height: 100px}}\"\n{ts}:src=\"${{2:url}}\"\n{ts}:fit=\"${{3:fit}}\">$4</el-image>"));
    m.insert("el-backtop".into(), "<el-backtop target=\"${1:.page-component__scroll .el-scrollbar__wrap}\">$2</el-backtop>".into());
    m.insert("el-drawer".into(), format!("<el-drawer\n{ts}title=\"${{1:我是标题}}\"\n{ts}:visible.sync=\"${{2:drawer}}\"\n{ts}:direction=\"${{3:direction}}\"\n{ts}:before-close=\"${{4:handleClose}}\">\n{ts}${{5:<span>我来啦!</span>}}\n</el-drawer>"));
    m
}
